name: alth
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - nuitka
      - numpy
      - ordered-set
      - pillow
      - pyqtdarktheme
      - pyside6
      - pytoshop
      - six
      - tqdm
      - typing_extensions
      - unitypy
