name: alth
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=*=openblas
  - nuitka
  - numpy
  - pillow
  - pip
  - pyinstaller
  - pysocks
  - six
  - pip:
    - pyside6
    - pytoshop
    - unitypy