name: alth
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pysocks
  - pip:
    - nuitka
    - numpy
    - ordered-set
    - pillow
    - pyinstaller
    - pyside6
    - pytoshop
    - six
    - unitypy