name: alth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - "blas=*=openblas"
  - numpy
  - pillow
  - pip
  - pyinstaller
  - pysocks
  - pip:
    - pytoshop
    - six
    - unitypy