on:
  push:
    branches:
        - "dev"
    # tags:
    #   - "*.*.*"

  workflow_dispatch:

env:
  app_name: AzurLaneTachieHelper-${{github.ref_name}}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check-out Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Dependencies
        id: prepare
        run: |
          pip install -r requirements.txt --ignore-requires-python
          git clone https://github.com/mdboom/pytoshop.git
          cd pytoshop
          python setup.py install
          cd ..
          python prepare.py

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          standalone: true
          onefile: false
          mingw64: false
          enable-plugins: pyside6
          nofollow-import-to: tkinter
          windows-icon-from-ico: ico\cheshire.ico
          include-data-files: |
            ${{steps.prepare.outputs.tpk}}=UnityPy\resources\
            i18n\*.qm=i18n\
          output-file: AzurLaneTachieHelper
    
      - name: Pack Files
        run: |
          cd build
          mv ../3rdparty app.dist/
          mv app.dist ${{env.app_name}}
          7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on ${{env.app_name}}.7z ${{env.app_name}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.app_name}}-x86_64
          path: build/${{env.app_name}}.7z
          retention-days: 21
